### 필요 데이터 전처리 작업 -> 최종 데이터 추출 process

In [1]:
# Reserve_Pandas - InteractiveShell
#설정변경코드
#변수 명이 두번 이상 출력되어도 모두 콘솔에서 보여줄 것
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

# InteractiveShell.ast_node_interactivity : 'all' | 'last' | 'last_expr' | 'none' (기본값은 'last_expr')

# 필요 모듈 import
import pandas as pd
import numpy as np
    
# 경고 메시지 무시 설정
import warnings
warnings.filterwarnings(action='ignore')

# pearson 상관관계 분석을 위한 package import
from scipy.stats import *

import seaborn as sns

In [2]:
data = pd.read_csv('data/수출데이터.csv')
data

    Unnamed: 0       날짜     수출건수      수출금액     수입건수      수입금액
0            0  2017-01   576924  40257000  1357603  37645403
1            1  2017-02   646704  43166536  1380523  36203282
2            2  2017-03   726472  48637832  1648350  42579492
3            3  2017-04   648450  50843799  1509868  37959391
4            4  2017-05   657406  44926979  1520646  39287764
..         ...      ...      ...       ...      ...       ...
62          62  2022-03  1403028  63790091  3543900  63607844
63          63  2022-04  1027167  57851066  3398510  60327559
64          64  2022-05  1100765  61591387  3365875  63191356
65          65  2022-06  1241866  57689934  3349002  60177051
66          66  2022-07   988961  60565944  3418775  65370835

[67 rows x 6 columns]

### 수출관련데이터 2018-03 ~ 2022-07 데이터 전처리 작업 진행

### 코로나 시기 정의
- 코로나 전 : 2018-03 ~ 2020.02
- 코로나 시기 : 2020.03 ~ 2022.02
- 전쟁 시기 : 2022.02 ~ ; 분석 기간에서 제외

In [3]:
# 2018.03 이후 데이터 추출
data_covidexp = data.loc[14:]
data_covidexp

    Unnamed: 0       날짜     수출건수      수출금액     수입건수      수입금액
14          14  2018-03   792813  51309932  1847813  44897838
15          15  2018-04   727349  49850235  1762609  43693963
16          16  2018-05   763659  50687750  1789768  44458729
17          17  2018-06   788826  51079375  1730889  45000164
18          18  2018-07   742392  51810255  1756375  44917044
19          19  2018-08   734664  51180449  1777271  44360778
20          20  2018-09   651137  50650208  1712344  41032928
21          21  2018-10   760934  54860310  1958340  48480618
22          22  2018-11   997647  51479530  1989739  46808199
23          23  2018-12   689676  48206793  1971887  44024694
24          24  2019-01   724445  46168934  2121240  45153389
25          25  2019-02   621348  39481803  1748298  36651437
26          26  2019-03   754196  47003206  2183681  41992349
27          27  2019-04   791438  48781156  2188788  45047164
28          28  2019-05   800751  45703948  2185460  43619667
29          29  2019-06   796854  44008404  2049066  40104812
30          30  2019-07   795298  46078221  2189639  43762245
31          31  2019-08   794112  44020065  2065221  42457250
32          32  2019-09   804837  44629053  2098148  38741473
33          33  2019-10   916254  46648756  2271691  41396517
34          34  2019-11  1218917  44040722  2391518  40729215
35          35  2019-12   888689  45668341  2397132  43687430
36          36  2020-01   735116  43103061  2339425  42718100
37          37  2020-02   798774  40911819  2377377  36977247
38          38  2020-03   912933  46167204  2657543  41803860
39          39  2020-04   766175  36270183  2296172  37932611
40          40  2020-05   799280  34854511  2316308  34661974
41          41  2020-06   985852  39214071  2354875  35794860
42          42  2020-07  1031635  42785144  2514501  38849185
43          43  2020-08   932166  39469231  2460518  35817929
44          44  2020-09  1126451  47819948  2898693  39400190
45          45  2020-10  1034425  44818534  2849716  39093795
46          46  2020-11  1306444  45751883  2943680  39944763
47          47  2020-12  1275069  51332449  3274735  44638246
48          48  2021-01  1063782  48006974  3216535  44456822
49          49  2021-02   991831  44706907  2779591  42404636
50          50  2021-03  1439462  53690914  3298165  49742555
51          51  2021-04  1184249  51225991  3346730  50891152
52          52  2021-05  1143835  50725161  3245257  47910522
53          53  2021-06  1513595  54778905  3101662  50429027
54          54  2021-07  1182251  55461518  3225209  53676256
55          55  2021-08  1122015  53165104  3180345  51581093
56          56  2021-09  1502399  55913862  3199940  51636341
57          57  2021-10  1104157  55660373  3356096  53847824
58          58  2021-11  1535829  60330542  3418506  57357549
59          59  2021-12  1322594  60734117  3657650  61159671
60          60  2022-01  1099910  55458997  3434132  60363866
61          61  2022-02  1017769  54154107  3131843  53316160
62          62  2022-03  1403028  63790091  3543900  63607844
63          63  2022-04  1027167  57851066  3398510  60327559
64          64  2022-05  1100765  61591387  3365875  63191356
65          65  2022-06  1241866  57689934  3349002  60177051
66          66  2022-07   988961  60565944  3418775  65370835

In [4]:
# 인덱스 1부터 시작 설정
data_covidexp.index = np.arange(1, len(data_covidexp)+1)

# Unnamed: 0 컬럼 삭제하기
data_covidexp.drop('Unnamed: 0', axis=1, inplace=True)
data_covidexp
# data_covidexp.to_csv('data/코로나시기수출데이터2.csv ') : 데이터 저장 (혹시 모를 상황 대비)

         날짜     수출건수      수출금액     수입건수      수입금액
1   2018-03   792813  51309932  1847813  44897838
2   2018-04   727349  49850235  1762609  43693963
3   2018-05   763659  50687750  1789768  44458729
4   2018-06   788826  51079375  1730889  45000164
5   2018-07   742392  51810255  1756375  44917044
6   2018-08   734664  51180449  1777271  44360778
7   2018-09   651137  50650208  1712344  41032928
8   2018-10   760934  54860310  1958340  48480618
9   2018-11   997647  51479530  1989739  46808199
10  2018-12   689676  48206793  1971887  44024694
11  2019-01   724445  46168934  2121240  45153389
12  2019-02   621348  39481803  1748298  36651437
13  2019-03   754196  47003206  2183681  41992349
14  2019-04   791438  48781156  2188788  45047164
15  2019-05   800751  45703948  2185460  43619667
16  2019-06   796854  44008404  2049066  40104812
17  2019-07   795298  46078221  2189639  43762245
18  2019-08   794112  44020065  2065221  42457250
19  2019-09   804837  44629053  2098148  38741473
20  2019-10   916254  46648756  2271691  41396517
21  2019-11  1218917  44040722  2391518  40729215
22  2019-12   888689  45668341  2397132  43687430
23  2020-01   735116  43103061  2339425  42718100
24  2020-02   798774  40911819  2377377  36977247
25  2020-03   912933  46167204  2657543  41803860
26  2020-04   766175  36270183  2296172  37932611
27  2020-05   799280  34854511  2316308  34661974
28  2020-06   985852  39214071  2354875  35794860
29  2020-07  1031635  42785144  2514501  38849185
30  2020-08   932166  39469231  2460518  35817929
31  2020-09  1126451  47819948  2898693  39400190
32  2020-10  1034425  44818534  2849716  39093795
33  2020-11  1306444  45751883  2943680  39944763
34  2020-12  1275069  51332449  3274735  44638246
35  2021-01  1063782  48006974  3216535  44456822
36  2021-02   991831  44706907  2779591  42404636
37  2021-03  1439462  53690914  3298165  49742555
38  2021-04  1184249  51225991  3346730  50891152
39  2021-05  1143835  50725161  3245257  47910522
40  2021-06  1513595  54778905  3101662  50429027
41  2021-07  1182251  55461518  3225209  53676256
42  2021-08  1122015  53165104  3180345  51581093
43  2021-09  1502399  55913862  3199940  51636341
44  2021-10  1104157  55660373  3356096  53847824
45  2021-11  1535829  60330542  3418506  57357549
46  2021-12  1322594  60734117  3657650  61159671
47  2022-01  1099910  55458997  3434132  60363866
48  2022-02  1017769  54154107  3131843  53316160
49  2022-03  1403028  63790091  3543900  63607844
50  2022-04  1027167  57851066  3398510  60327559
51  2022-05  1100765  61591387  3365875  63191356
52  2022-06  1241866  57689934  3349002  60177051
53  2022-07   988961  60565944  3418775  65370835

In [5]:
# 데이터 속성 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  67 non-null     int64
 1   날짜          67 non-null     object
 2   수출건수        67 non-null     int64
 3   수출금액        67 non-null     int64
 4   수입건수        67 non-null     int64
 5   수입금액        67 non-null     int64
dtypes: int64(5), object(1)
memory usage: 2.9+ KB

In [6]:
# 날짜 object -> Date 로 형식 변환[datetime64]
# Use the pandas to_datetime function to parse the column as DateTime. 
# Also, by using infer_datetime_format=True, 
# it will automatically detect the format and convert the mentioned column to DateTime.
data['날짜'] = pd.to_datetime(data['날짜'], infer_datetime_format=True)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  67 non-null     int64
 1   날짜          67 non-null     datetime64[ns]
 2   수출건수        67 non-null     int64
 3   수출금액        67 non-null     int64
 4   수입건수        67 non-null     int64
 5   수입금액        67 non-null     int64
dtypes: datetime64[ns](1), int64(5)
memory usage: 3.2 KB

In [8]:
import matplotlib.dates as mdates
# data_covidexp.drop(labels=['수출건수','수입건수','수입금액'],axis=1,inplace=True)
data_covidexp

         날짜     수출건수      수출금액     수입건수      수입금액
1   2018-03   792813  51309932  1847813  44897838
2   2018-04   727349  49850235  1762609  43693963
3   2018-05   763659  50687750  1789768  44458729
4   2018-06   788826  51079375  1730889  45000164
5   2018-07   742392  51810255  1756375  44917044
6   2018-08   734664  51180449  1777271  44360778
7   2018-09   651137  50650208  1712344  41032928
8   2018-10   760934  54860310  1958340  48480618
9   2018-11   997647  51479530  1989739  46808199
10  2018-12   689676  48206793  1971887  44024694
11  2019-01   724445  46168934  2121240  45153389
12  2019-02   621348  39481803  1748298  36651437
13  2019-03   754196  47003206  2183681  41992349
14  2019-04   791438  48781156  2188788  45047164
15  2019-05   800751  45703948  2185460  43619667
16  2019-06   796854  44008404  2049066  40104812
17  2019-07   795298  46078221  2189639  43762245
18  2019-08   794112  44020065  2065221  42457250
19  2019-09   804837  44629053  2098148  38741473
20  2019-10   916254  46648756  2271691  41396517
21  2019-11  1218917  44040722  2391518  40729215
22  2019-12   888689  45668341  2397132  43687430
23  2020-01   735116  43103061  2339425  42718100
24  2020-02   798774  40911819  2377377  36977247
25  2020-03   912933  46167204  2657543  41803860
26  2020-04   766175  36270183  2296172  37932611
27  2020-05   799280  34854511  2316308  34661974
28  2020-06   985852  39214071  2354875  35794860
29  2020-07  1031635  42785144  2514501  38849185
30  2020-08   932166  39469231  2460518  35817929
31  2020-09  1126451  47819948  2898693  39400190
32  2020-10  1034425  44818534  2849716  39093795
33  2020-11  1306444  45751883  2943680  39944763
34  2020-12  1275069  51332449  3274735  44638246
35  2021-01  1063782  48006974  3216535  44456822
36  2021-02   991831  44706907  2779591  42404636
37  2021-03  1439462  53690914  3298165  49742555
38  2021-04  1184249  51225991  3346730  50891152
39  2021-05  1143835  50725161  3245257  47910522
40  2021-06  1513595  54778905  3101662  50429027
41  2021-07  1182251  55461518  3225209  53676256
42  2021-08  1122015  53165104  3180345  51581093
43  2021-09  1502399  55913862  3199940  51636341
44  2021-10  1104157  55660373  3356096  53847824
45  2021-11  1535829  60330542  3418506  57357549
46  2021-12  1322594  60734117  3657650  61159671
47  2022-01  1099910  55458997  3434132  60363866
48  2022-02  1017769  54154107  3131843  53316160
49  2022-03  1403028  63790091  3543900  63607844
50  2022-04  1027167  57851066  3398510  60327559
51  2022-05  1100765  61591387  3365875  63191356
52  2022-06  1241866  57689934  3349002  60177051
53  2022-07   988961  60565944  3418775  65370835

In [9]:
# 무역수지 컬럼 추가 작업
data_무역수지 = pd.read_csv('data/수출입총괄.csv')
data_무역수지.drop(labels=['수출건수', '수출금액', '수입건수', '수입금액', '(단위1000USD)'], axis=1, inplace=True)
data_무역수지1 = data_무역수지[1:]
data_무역수지1

         기간        무역수지
1   2017.01   2,611,597
2   2017.02   6,963,254
3   2017.03   6,058,340
4   2017.04  12,884,408
5   2017.05   5,639,215
..      ...         ...
63  2022.03     182,246
64  2022.04  -2,476,493
65  2022.05  -1,599,969
66  2022.06  -2,487,117
67  2022.07  -4,804,890

[67 rows x 2 columns]

In [10]:
# 데이터 병합전 전처리 작업 (날짜 형식 & 무역수지 값 형식(쉼표 제거))
date_li = []
for date in data_무역수지1['기간']:
    date_li.append(date.replace('.','-'))

eco_li = [] # 무역수지 empty list
for eco in data_무역수지1['무역수지']:
    eco_li.append(eco.replace(',',''))

data = {
    '날짜':date_li,
    '무역수지':eco_li
}

df_무역수지 = pd.DataFrame(data)
df_무역수지

         날짜      무역수지
0   2017-01   2611597
1   2017-02   6963254
2   2017-03   6058340
3   2017-04  12884408
4   2017-05   5639215
..      ...       ...
62  2022-03    182246
63  2022-04  -2476493
64  2022-05  -1599969
65  2022-06  -2487117
66  2022-07  -4804890

[67 rows x 2 columns]

In [11]:
# 10월 데이터 값이 1로 표현되어 전처리 작업 수행

# 1. '-' 제거 작업
oct_li = []
for d in df_무역수지['날짜']:
    oct_li.append(d.split('-'))

# 2. 10월달 해당 값이 1로 표현됨 : 1 -> 10 변경 전처리 작업
for i in range (len(oct_li)):
    if len(oct_li[i][1]) == 1:
        oct_li[i][1] += '0'
oct_li

# 3. 20xx-xx 형식으로 다시 concate 후 oct_li1로 append 
oct_li1 = []
for date in oct_li:
    d = date[0] + '-' + date[1]
    oct_li1.append(d)
oct_li1

[['2017', '01'],
 ['2017', '02'],
 ['2017', '03'],
 ['2017', '04'],
 ['2017', '05'],
 ['2017', '06'],
 ['2017', '07'],
 ['2017', '08'],
 ['2017', '09'],
 ['2017', '10'],
 ['2017', '11'],
 ['2017', '12'],
 ['2018', '01'],
 ['2018', '02'],
 ['2018', '03'],
 ['2018', '04'],
 ['2018', '05'],
 ['2018', '06'],
 ['2018', '07'],
 ['2018', '08'],
 ['2018', '09'],
 ['2018', '10'],
 ['2018', '11'],
 ['2018', '12'],
 ['2019', '01'],
 ['2019', '02'],
 ['2019', '03'],
 ['2019', '04'],
 ['2019', '05'],
 ['2019', '06'],
 ['2019', '07'],
 ['2019', '08'],
 ['2019', '09'],
 ['2019', '10'],
 ['2019', '11'],
 ['2019', '12'],
 ['2020', '01'],
 ['2020', '02'],
 ['2020', '03'],
 ['2020', '04'],
 ['2020', '05'],
 ['2020', '06'],
 ['2020', '07'],
 ['2020', '08'],
 ['2020', '09'],
 ['2020', '10'],
 ['2020', '11'],
 ['2020', '12'],
 ['2021', '01'],
 ['2021', '02'],
 ['2021', '03'],
 ['2021', '04'],
 ['2021', '05'],
 ['2021', '06'],
 ['2021', '07'],
 ['2021', '08'],
 ['2021', '09'],
 ['2021', '10'],
 ['2021', '11'],
 ['2021', '12'],
 ['2022', '01'],
 ['2022', '02'],
 ['2022', '03'],
 ['2022', '04'],
 ['2022', '05'],
 ['2022', '06'],
 ['2022', '07']]

['2017-01',
 '2017-02',
 '2017-03',
 '2017-04',
 '2017-05',
 '2017-06',
 '2017-07',
 '2017-08',
 '2017-09',
 '2017-10',
 '2017-11',
 '2017-12',
 '2018-01',
 '2018-02',
 '2018-03',
 '2018-04',
 '2018-05',
 '2018-06',
 '2018-07',
 '2018-08',
 '2018-09',
 '2018-10',
 '2018-11',
 '2018-12',
 '2019-01',
 '2019-02',
 '2019-03',
 '2019-04',
 '2019-05',
 '2019-06',
 '2019-07',
 '2019-08',
 '2019-09',
 '2019-10',
 '2019-11',
 '2019-12',
 '2020-01',
 '2020-02',
 '2020-03',
 '2020-04',
 '2020-05',
 '2020-06',
 '2020-07',
 '2020-08',
 '2020-09',
 '2020-10',
 '2020-11',
 '2020-12',
 '2021-01',
 '2021-02',
 '2021-03',
 '2021-04',
 '2021-05',
 '2021-06',
 '2021-07',
 '2021-08',
 '2021-09',
 '2021-10',
 '2021-11',
 '2021-12',
 '2022-01',
 '2022-02',
 '2022-03',
 '2022-04',
 '2022-05',
 '2022-06',
 '2022-07']

In [12]:
data1 = {
    '날짜':oct_li1,
    '무역수지':eco_li
}

df_무역수지1 = pd.DataFrame(data1)
df_무역수지1[14:]

         날짜      무역수지
14  2018-03   6412094
15  2018-04   6156273
16  2018-05   6229021
17  2018-06   6079212
18  2018-07   6893211
19  2018-08   6819671
20  2018-09   9617280
21  2018-10   6379692
22  2018-11   4671331
23  2018-12   4182099
24  2019-01   1015545
25  2019-02   2830366
26  2019-03   5010857
27  2019-04   3733992
28  2019-05   2084281
29  2019-06   3903592
30  2019-07   2315976
31  2019-08   1562815
32  2019-09   5887580
33  2019-10   5252239
34  2019-11   3311507
35  2019-12   1980912
36  2020-01    384960
37  2020-02   3934572
38  2020-03   4363344
39  2020-04  -1662429
40  2020-05    192537
41  2020-06   3419211
42  2020-07   3935959
43  2020-08   3651302
44  2020-09   8419758
45  2020-10   5724739
46  2020-11   5807120
47  2020-12   6694203
48  2021-01   3550152
49  2021-02   2302271
50  2021-03   3948359
51  2021-04    334840
52  2021-05   2814640
53  2021-06   4349878
54  2021-07   1785262
55  2021-08   1584011
56  2021-09   4277521
57  2021-10   1812548
58  2021-11   2972993
59  2021-12   -425554
60  2022-01  -4904869
61  2022-02    837947
62  2022-03    182246
63  2022-04  -2476493
64  2022-05  -1599969
65  2022-06  -2487117
66  2022-07  -4804890

In [13]:
# 1803 2207 기간 설정
df_무역수지2 = df_무역수지1[14:]
df_무역수지2.index = (np.arange(1, len(df_무역수지2)+1))
df_무역수지2

         날짜      무역수지
1   2018-03   6412094
2   2018-04   6156273
3   2018-05   6229021
4   2018-06   6079212
5   2018-07   6893211
6   2018-08   6819671
7   2018-09   9617280
8   2018-10   6379692
9   2018-11   4671331
10  2018-12   4182099
11  2019-01   1015545
12  2019-02   2830366
13  2019-03   5010857
14  2019-04   3733992
15  2019-05   2084281
16  2019-06   3903592
17  2019-07   2315976
18  2019-08   1562815
19  2019-09   5887580
20  2019-10   5252239
21  2019-11   3311507
22  2019-12   1980912
23  2020-01    384960
24  2020-02   3934572
25  2020-03   4363344
26  2020-04  -1662429
27  2020-05    192537
28  2020-06   3419211
29  2020-07   3935959
30  2020-08   3651302
31  2020-09   8419758
32  2020-10   5724739
33  2020-11   5807120
34  2020-12   6694203
35  2021-01   3550152
36  2021-02   2302271
37  2021-03   3948359
38  2021-04    334840
39  2021-05   2814640
40  2021-06   4349878
41  2021-07   1785262
42  2021-08   1584011
43  2021-09   4277521
44  2021-10   1812548
45  2021-11   2972993
46  2021-12   -425554
47  2022-01  -4904869
48  2022-02    837947
49  2022-03    182246
50  2022-04  -2476493
51  2022-05  -1599969
52  2022-06  -2487117
53  2022-07  -4804890

In [14]:
data_covidexp['무역수지'] = df_무역수지2['무역수지']
data_covidexp

         날짜     수출건수      수출금액     수입건수      수입금액      무역수지
1   2018-03   792813  51309932  1847813  44897838   6412094
2   2018-04   727349  49850235  1762609  43693963   6156273
3   2018-05   763659  50687750  1789768  44458729   6229021
4   2018-06   788826  51079375  1730889  45000164   6079212
5   2018-07   742392  51810255  1756375  44917044   6893211
6   2018-08   734664  51180449  1777271  44360778   6819671
7   2018-09   651137  50650208  1712344  41032928   9617280
8   2018-10   760934  54860310  1958340  48480618   6379692
9   2018-11   997647  51479530  1989739  46808199   4671331
10  2018-12   689676  48206793  1971887  44024694   4182099
11  2019-01   724445  46168934  2121240  45153389   1015545
12  2019-02   621348  39481803  1748298  36651437   2830366
13  2019-03   754196  47003206  2183681  41992349   5010857
14  2019-04   791438  48781156  2188788  45047164   3733992
15  2019-05   800751  45703948  2185460  43619667   2084281
16  2019-06   796854  44008404  2049066  40104812   3903592
17  2019-07   795298  46078221  2189639  43762245   2315976
18  2019-08   794112  44020065  2065221  42457250   1562815
19  2019-09   804837  44629053  2098148  38741473   5887580
20  2019-10   916254  46648756  2271691  41396517   5252239
21  2019-11  1218917  44040722  2391518  40729215   3311507
22  2019-12   888689  45668341  2397132  43687430   1980912
23  2020-01   735116  43103061  2339425  42718100    384960
24  2020-02   798774  40911819  2377377  36977247   3934572
25  2020-03   912933  46167204  2657543  41803860   4363344
26  2020-04   766175  36270183  2296172  37932611  -1662429
27  2020-05   799280  34854511  2316308  34661974    192537
28  2020-06   985852  39214071  2354875  35794860   3419211
29  2020-07  1031635  42785144  2514501  38849185   3935959
30  2020-08   932166  39469231  2460518  35817929   3651302
31  2020-09  1126451  47819948  2898693  39400190   8419758
32  2020-10  1034425  44818534  2849716  39093795   5724739
33  2020-11  1306444  45751883  2943680  39944763   5807120
34  2020-12  1275069  51332449  3274735  44638246   6694203
35  2021-01  1063782  48006974  3216535  44456822   3550152
36  2021-02   991831  44706907  2779591  42404636   2302271
37  2021-03  1439462  53690914  3298165  49742555   3948359
38  2021-04  1184249  51225991  3346730  50891152    334840
39  2021-05  1143835  50725161  3245257  47910522   2814640
40  2021-06  1513595  54778905  3101662  50429027   4349878
41  2021-07  1182251  55461518  3225209  53676256   1785262
42  2021-08  1122015  53165104  3180345  51581093   1584011
43  2021-09  1502399  55913862  3199940  51636341   4277521
44  2021-10  1104157  55660373  3356096  53847824   1812548
45  2021-11  1535829  60330542  3418506  57357549   2972993
46  2021-12  1322594  60734117  3657650  61159671   -425554
47  2022-01  1099910  55458997  3434132  60363866  -4904869
48  2022-02  1017769  54154107  3131843  53316160    837947
49  2022-03  1403028  63790091  3543900  63607844    182246
50  2022-04  1027167  57851066  3398510  60327559  -2476493
51  2022-05  1100765  61591387  3365875  63191356  -1599969
52  2022-06  1241866  57689934  3349002  60177051  -2487117
53  2022-07   988961  60565944  3418775  65370835  -4804890

In [15]:
# 전처리 작업 완료된 파일 저장
data_covidexp.to_csv('output/대한민국수출데이터(최종).csv')

### 날짜 / 전세계 코로나 추세 / 국내 코로나 추세  / 수출금액 DataFrame 만들기

In [16]:
# df.drop(labels=['col1','col2'],axis=1,inplace=True)
data1 = pd.read_csv('data/코로나시기수출데이터.csv') 
# data1_전처리 = data1.drop(labels=['수출건수','수입건수','수입금액'],axis=1)
# data1_전처리
data_final = data1.loc[24:48]
data_final.index = np.arange(1, len(data_final)+1)
코로나시기_국내수출 = data_final.drop(labels=['Unnamed: 0'],axis=1)
코로나시기_국내수출
# 코로나시기_국내수출.info()
# 코로나시기_국내수출
# df.reset_index(inplace=True)
# df.index = np.arange(1, len(df) + 1)

         날짜      수출금액
1   2020-03  46167204
2   2020-04  36270183
3   2020-05  34854511
4   2020-06  39214071
5   2020-07  42785144
6   2020-08  39469231
7   2020-09  47819948
8   2020-10  44818534
9   2020-11  45751883
10  2020-12  51332449
11  2021-01  48006974
12  2021-02  44706907
13  2021-03  53690914
14  2021-04  51225991
15  2021-05  50725161
16  2021-06  54778905
17  2021-07  55461518
18  2021-08  53165104
19  2021-09  55913862
20  2021-10  55660373
21  2021-11  60330542
22  2021-12  60734117
23  2022-01  55458997
24  2022-02  54154107

In [17]:
df = pd.read_csv('data/국내확진자월단위추세.csv')
df.rename(columns = {'Republic of Korea(확진자)':'국내월별확진자'}, inplace = True)
df.index = np.arange(1, len(df)+1)
df.drop(labels=['Unnamed: 0'],axis=1,inplace=True)
코로나시기_국내월별확진자 = df.loc[1:24]
코로나시기_국내월별확진자

         날짜  국내월별확진자
1   2020-03     6855
2   2020-04      979
3   2020-05      703
4   2020-06     1331
5   2020-07     1506
6   2020-08     5642
7   2020-09     3865
8   2020-10     2699
9   2020-11     7688
10  2020-12    26523
11  2021-01    17476
12  2021-02    11467
13  2021-03    13415
14  2021-04    18919
15  2021-05    18339
16  2021-06    16623
17  2021-07    41384
18  2021-08    53075
19  2021-09    59867
20  2021-10    53413
21  2021-11    82527
22  2021-12   183608
23  2022-01   214864
24  2022-02  2288757

In [18]:
world = pd.read_csv('data/코로나_공공API_전세계데이터(preprocessed).csv')

world.drop(labels=['Unnamed: 0', '일자', '국가코드', '누적 확진자', '사망자', '누적 사망자', '대륙명(영문)',
                  '대륙명(한글)', '국가명(영문)', '국가명(한글)'], axis=1, inplace=True)
world.to_csv('test2', encoding='utf-8')
world

        확진자   월단위 일자
0         0  2020-01
1         0  2020-01
2         0  2020-01
3         0  2020-01
4         0  2020-01
...     ...      ...
187195    0  2022-08
187196    0  2022-08
187197    0  2022-08
187198    0  2022-08
187199    0  2022-08

[187200 rows x 2 columns]

In [19]:
# 전세계코로나 추세를 월별 데이터로 pivot table로 나타내기
pivot = pd.pivot_table(world, values='확진자', index=['월단위 일자'], aggfunc='sum')
data = pivot
df = pd.DataFrame(data)
df.info()
df['확진자'].astype(object)
df['확진자'][2:26]

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 2020-01 to 2022-08
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   확진자     32 non-null     int64
dtypes: int64(1)
memory usage: 384.0+ bytes

월단위 일자
2020-01        9721
2020-02       74833
2020-03      747267
2020-04     2311509
2020-05     2891921
2020-06     4277169
2020-07     7036270
2020-08     8288030
2020-09     8690268
2020-10    12367392
2020-11    17058500
2020-12    19035159
2021-01    19732292
2021-02    11025349
2021-03    14419055
2021-04    21977123
2021-05    20185183
2021-06    11425729
2021-07    15770621
2021-08    19692105
2021-09    16084219
2021-10    13336346
2021-11    15376548
2021-12    24616793
2022-01    89153380
2022-02    58525895
2022-03    51461996
2022-04    25368242
2022-05    17768489
2022-06    18806589
2022-07    30744826
2022-08    11329018
Name: 확진자, dtype: object

월단위 일자
2020-03      747267
2020-04     2311509
2020-05     2891921
2020-06     4277169
2020-07     7036270
2020-08     8288030
2020-09     8690268
2020-10    12367392
2020-11    17058500
2020-12    19035159
2021-01    19732292
2021-02    11025349
2021-03    14419055
2021-04    21977123
2021-05    20185183
2021-06    11425729
2021-07    15770621
2021-08    19692105
2021-09    16084219
2021-10    13336346
2021-11    15376548
2021-12    24616793
2022-01    89153380
2022-02    58525895
Name: 확진자, dtype: int64

In [20]:
# for x in df['확진자'][2:26]:
#     print(x)
    
전세계코로나월별데이터 = [ x for x in df['확진자'][2:26] ]
전세계코로나월별데이터
len(전세계코로나월별데이터)

[747267,
 2311509,
 2891921,
 4277169,
 7036270,
 8288030,
 8690268,
 12367392,
 17058500,
 19035159,
 19732292,
 11025349,
 14419055,
 21977123,
 20185183,
 11425729,
 15770621,
 19692105,
 16084219,
 13336346,
 15376548,
 24616793,
 89153380,
 58525895]

24

In [21]:
국내 = pd.read_csv('data/코로나바이러스감염증-19_확진환자_발생현황_220821.csv')
국내

             일자        계(명)     국내발생(명) 해외유입(명)   사망(명)
0         누적(명)  22,240,331  22,185,445  54,886  26,044
1    2020-01-20           1           -       1       -
2    2020-01-21           0           -       -       -
3    2020-01-22           0           -       -       -
4    2020-01-23           0           -       -       -
..          ...         ...         ...     ...     ...
941  2022-08-17     180,771     180,206     565      42
942  2022-08-18     178,553     177,921     632      61
943  2022-08-19     138,812     138,347     465      83
944  2022-08-20     129,411     128,919     492      84
945  2022-08-21     110,944     110,548     396      64

[946 rows x 5 columns]

In [22]:
# 국내 월별 코로나 확진자 수 구하기
국내1 = 국내.iloc[1:949]
dates = 국내1['일자']
date_li = []
for date in dates:
    x = date[:4] + '-' + date[5:7]
    date_li.append(x)
date_li

['2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08']

In [23]:
num_li = []
for num in 국내1['계(명)']:
    n = num.replace(',', '')
    num_li.append(n)
len(num_li)

945

In [24]:
국내1['계(명)_쉼표제거'] = num_li

In [25]:
# 국내 DataFrame 에 date_li 넣어주기
국내1['월날짜'] = date_li
date_li
국내1 = 국내1.astype({'계(명)_쉼표제거':'int'})
# 국내1['계(명)_쉼표제거'].astype('int')
# 국내1.drop(labels=['계(명)','국내발생(명)','해외유입(명)','사망(명)'],axis=1, inplace=True)
국내1.info()
국내1

['2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-01',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-02',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-03',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-04',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-05',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-06',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-07',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-08',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-09',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-10',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-11',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2020-12',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-01',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-02',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-03',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-04',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-05',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-06',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-07',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-08',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-09',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-10',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-11',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2021-12',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-01',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-02',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-03',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-04',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-05',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-06',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-07',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08',
 '2022-08']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 1 to 945
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   일자         945 non-null    object
 1   계(명)       945 non-null    object
 2   국내발생(명)    945 non-null    object
 3   해외유입(명)    945 non-null    object
 4   사망(명)      945 non-null    object
 5   계(명)_쉼표제거  945 non-null    int32
 6   월날짜        945 non-null    object
dtypes: int32(1), object(6)
memory usage: 25.9+ KB

             일자     계(명)  국내발생(명) 해외유입(명) 사망(명)  계(명)_쉼표제거      월날짜
1    2020-01-20        1        -       1     -          1  2020-01
2    2020-01-21        0        -       -     -          0  2020-01
3    2020-01-22        0        -       -     -          0  2020-01
4    2020-01-23        0        -       -     -          0  2020-01
5    2020-01-24        1        -       1     -          1  2020-01
..          ...      ...      ...     ...   ...        ...      ...
941  2022-08-17  180,771  180,206     565    42     180771  2022-08
942  2022-08-18  178,553  177,921     632    61     178553  2022-08
943  2022-08-19  138,812  138,347     465    83     138812  2022-08
944  2022-08-20  129,411  128,919     492    84     129411  2022-08
945  2022-08-21  110,944  110,548     396    64     110944  2022-08

[945 rows x 7 columns]

In [26]:
# 국내1 -> pivot table
국내1_pivot = pd.pivot_table(국내1, values='계(명)_쉼표제거', index=['월날짜'], aggfunc='sum')
data = 국내1_pivot
df_국내1 = pd.DataFrame(data)
df_국내1

         계(명)_쉼표제거
월날짜
2020-01         11
2020-02       2920
2020-03       6855
2020-04        979
2020-05        703
2020-06       1331
2020-07       1506
2020-08       5641
2020-09       3865
2020-10       2700
2020-11       7688
2020-12      26527
2021-01      17471
2021-02      11467
2021-03      13414
2021-04      18927
2021-05      18331
2021-06      16623
2021-07      41374
2021-08      53077
2021-09      59857
2021-10      53415
2021-11      82517
2021-12     183594
2022-01     214817
2022-02    2288490
2022-03    9960500
2022-04    4142579
2022-05     866072
2022-06     255874
2022-07    1416677
2022-08    2464529

In [27]:
df_국내1.to_csv('국내월별확진자수.csv')

In [28]:
pd.date_range(start='2020-03', end='2022-02', freq='m')

DatetimeIndex(['2020-03-31', '2020-04-30', '2020-05-31', '2020-06-30',
               '2020-07-31', '2020-08-31', '2020-09-30', '2020-10-31',
               '2020-11-30', '2020-12-31', '2021-01-31', '2021-02-28',
               '2021-03-31', '2021-04-30', '2021-05-31', '2021-06-30',
               '2021-07-31', '2021-08-31', '2021-09-30', '2021-10-31',
               '2021-11-30', '2021-12-31', '2022-01-31'],
              dtype='datetime64[ns]', freq='M')

In [29]:
# dataframe 병합을 위한 월날짜 df 생성
월날짜 = [d.strftime('%Y-%m') for d in pd.date_range(start='2020-03',end='2022-03', freq='m')]

In [30]:
data = {
    '날짜':월날짜,
    '전세계월별확진자':전세계코로나월별데이터
}
코로나시기_전세계월별확진자 = pd.DataFrame(data)
코로나시기_전세계월별확진자

df1 = 코로나시기_국내수출 
df2 = 코로나시기_국내월별확진자
df3 = 코로나시기_전세계월별확진자

         날짜  전세계월별확진자
0   2020-03    747267
1   2020-04   2311509
2   2020-05   2891921
3   2020-06   4277169
4   2020-07   7036270
5   2020-08   8288030
6   2020-09   8690268
7   2020-10  12367392
8   2020-11  17058500
9   2020-12  19035159
10  2021-01  19732292
11  2021-02  11025349
12  2021-03  14419055
13  2021-04  21977123
14  2021-05  20185183
15  2021-06  11425729
16  2021-07  15770621
17  2021-08  19692105
18  2021-09  16084219
19  2021-10  13336346
20  2021-11  15376548
21  2021-12  24616793
22  2022-01  89153380
23  2022-02  58525895

In [31]:
# 코로나 수출 필요 데이터 -> df_covidExp DataFrame 으로 생성; covid export
df_covidExp=pd.read_csv('output/코로나수출_필요데이터(최종).csv')
del df_covidExp['Unnamed: 0']
df_covidExp
df_covidExp.info()

         날짜      수출금액  국내월별확진자  전세계월별확진자
0   2020-03  46167204     6855    747267
1   2020-04  36270183      979   2311509
2   2020-05  34854511      703   2891921
3   2020-06  39214071     1331   4277169
4   2020-07  42785144     1506   7036270
5   2020-08  39469231     5642   8288030
6   2020-09  47819948     3865   8690268
7   2020-10  44818534     2699  12367392
8   2020-11  45751883     7688  17058500
9   2020-12  51332449    26523  19035159
10  2021-01  48006974    17476  19732292
11  2021-02  44706907    11467  11025349
12  2021-03  53690914    13415  14419055
13  2021-04  51225991    18919  21977123
14  2021-05  50725161    18339  20185183
15  2021-06  54778905    16623  11425729
16  2021-07  55461518    41384  15770621
17  2021-08  53165104    53075  19692105
18  2021-09  55913862    59867  16084219
19  2021-10  55660373    53413  13336346
20  2021-11  60330542    82527  15376548
21  2021-12  60734117   183608  24616793
22  2022-01  55458997   214864  89153380
23  2022-02  54154107  2288757  58525895

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   날짜        24 non-null     object
 1   수출금액      24 non-null     int64
 2   국내월별확진자   24 non-null     int64
 3   전세계월별확진자  24 non-null     int64
dtypes: int64(3), object(1)
memory usage: 736.0+ bytes